version: '3'
services:

  rps-web:
    build:
      context: ./rps-web/
    container_name: rps-web
    image: rps-web
    links:
      - rps-service:rps-service
    ports:
      - 80:80

  rps-service:
    build:
      context: ./rps-service/
    container_name: rps-service
    image: rps-service
    ports:
      - 8080:8080